---
- name: Creates directory
  file:
    path: ~/backend_app
    state: directory

- name: Copy files
  copy:
    src: "artifact.tar.gz"
    dest: "~/backend_app/artifact.tar.gz"
  

- name: Extract 
  unarchive:
    src: "~/backend_app/artifact.tar.gz"
    dest: "~/backend_app/"
    remote_src: yes


- name: "Install dependencies for project"
  shell: |
    cd ~/backend_app
    npm install

- name: "Executing node"
  shell: |
    export
    pm2 stop default
    pm2 start npm -- start
    pm2 start main.js
  register: execute_node
- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

  args:
    chdir: ~/backend_app/backend/dist
  environment:
    - ENVIRONMENT: production
    - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"     
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
    - TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
    - TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}" 
    - AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID')}}"
    - AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY')}}"
    - AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION')}}" 
    - TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES')}}"
