---

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy files
  template:
    src: "files/artifact.tar.gz"
    dest: "~/web/artifact.tar.gz"

- name: Executing node
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
    pm2 start ~/web/artifact.tar.gz -f
  